### ISSUE TITLE
Exception on execution cell

### ISSUE THREAD

**Issue by evgraph** [degivan/code-block-cells#1]
Step to reproduce:
1. Create new project
2. Create file with the following content
3. Execute second cell

```python
print(1)
```

```java
null
java.lang.NullPointerException
	at com.degtiarenko.plugin.execution.CellExecutionHandler.<init>(CellExecutionHandler.java:31)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.degtiarenko.plugin.execution.CellExecutionManager.getHandler(CellExecutionManager.java:19)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.executeInConsole(PyExecuteCellAction.java:254)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.lambda$showConsoleAndExecuteCode$0(PyExecuteCellAction.java:87)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.lambda$selectConsole$1(PyExecuteCellAction.java:147)
	at com.intellij.execution.ExecutionHelper.selectContentDescriptor(ExecutionHelper.java:269)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.selectConsole(PyExecuteCellAction.java:144)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.findCodeExecutor(PyExecuteCellAction.java:204)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.showConsoleAndExecuteCode(PyExecuteCellAction.java:87)
	at com.degtiarenko.plugin.execution.PyExecuteCellAction.actionPerformed(PyExecuteCellAction.java:56)
	at com.degtiarenko.plugin.CellLineProvider$1$1$1.actionPerformed(CellLineProvider.java:86)
```

**Comment by degivan** [comment]
Here's solution, which creates new console(if old is not initialized): #4 . Problem is that I can't really find a way to force program to wait till selected console is initialized. It happens within PyDevConsoleRunner class, and I can't get instance of it corresponding to selected console
